
mybatis:
  mapper-locations: classpath*:com/rzw/dao/mapper/**/*Mapper.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.rzw.web.controller: debug
server:
  port: 8081